import Head from "next/head";
import styled from "styled-components";

export default function Home() {
  return (
    <>
      <Head>
        <title>KlangundTipi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <StyledWelcomeSection id="welcome">
          <StyledWelcomeTitle>
            Erlebe Sie einen Abend mit Klang und Speisen in einem traditionellen Tipi
          </StyledWelcomeTitle>
          <StyledWelcomeText>
            Genießen Sie mit Ihren Freunden/Familie einen unvergesslichen Abend am Lagerfeuer, mit Speisen und Klang in
            einem traditionellen Tipi. Sie haben die Möglichkeit aus verschiedenen Modulen sich Ihren Abend selbst zu gestalten.
          </StyledWelcomeText>
          <StyledCalltoActionbutton href="#price">Zum Angebot</StyledCalltoActionbutton>
        </StyledWelcomeSection>
        <StyledAboutUsSection id="aboutUs">
          <h2>über Uns</h2>
          <div>
            <p>
              Mein Name ist Christiane Wolf. Ich bin seit 20 Jahren als Ergotherapeutin tätig und weiß wie wichtig
              Entspannung für unsere Gesundheit ist. 2017 habe ich die Peter Hess- klang-Methode entdeckt und bin über
              die vielen Möglichkeiten der Klangmassagen und Klang-Fantasie-reisen fasziniert. Sie können uns helfen
              besser und leichter in die Entspannung zu kommen. Die ist auch in unseren Hirnströmen messbar.
            </p>
            <p>
              Mein Name ist Stefan Blass. Ich war über 40 Jahre selbständig in der Gastronomie tätig. Während dieser
              Zeit habe ich die Leidenschaft für die Kultur der Plain-Indianerstämme entdeckt. Daraus erfolgte der
              Gedanke in einem Indianertipi mit interessierten Menschen gemeinsam indianische Abende zu gestalten.
            </p>
            <p>
              Durch dieses gemeinsamen Interessen kam uns der Gedanke die Tipiabende mit Speisen und Klangreisen zu
              erweitern.
            </p>
          </div>
        </StyledAboutUsSection>
        <StyledTeepeeSection>
          <h2>ein Abend im traditionellen Tipi</h2>
          <p>
            In einem Tipi, umgeben von der Natur, knistert das Lagerfeuer leise. Der Duft von Holz und frischer Luft
            füllt den Raum. Kerzenlicht flackert sanft, während wir den Abend in Ruhe und Wärme genießen. Ein magischer
            Moment.
          </p>
        </StyledTeepeeSection>
        <StyledSoundJourneySection>
          <h2>eine Reise mit Klang</h2>
          <p>
            Die Peter Hess-Klangmethode nutzt speziell entwickelte Klangschalen, deren Schwingungen Körper und Geist
            entspannen. Dabei werden die Schalen auf den Körper gelegt und angeschlagen, um durch Vibrationen Blockaden
            zu lösen und die Selbstheilungskräfte zu aktivieren. Sie fördert Tiefenentspannung, Stressabbau und das
            Wohlbefinden durch harmonische Klänge und sanfte Vibrationen.
          </p>
        </StyledSoundJourneySection>
        <StyledPriceSection id="price">
          <h2>unser Angebot</h2>
          <p>
            Genießen Sie mit Ihren Freunden/Familie einen unvergesslichen Abend am Lagerfeuer, mit Speisen und Klang in
            einem Tipi. Sie haben die Möglichkeit aus verschiedenen Modulen sich Ihren Abend selbst zu gestalten. 1.
            Tipianmietung ohne Service pro Person ab zwei Personen 15 € 2. Tipiabend mit Verpflegung 3 Gängemenü nach
            Absprache und Getränke Preis nach Absprache 3. Tipiabend mit Klang-Fantasie-Reise (ca. 30 min.) Preis pro
            Person für 2 Personen 36 € jede weitere Person 15 € 4. Tipiabend incl. Übernachtung (Schlafsäcke sind selbst
            mitzubringen) pro Person 15 € Feuerholz wird separat berechnet. Anmietung für besondere Anlässe ,
            Geburtstage, Hochzeiten Todesfälle 150€
          </p>
        </StyledPriceSection>
        <StyledContactSection id="contact">
          <h2>Kontakt</h2>
          <p>Max Mustermann<br/>
            Musterstraße 1<br/>Musterstadt 12345<br/>
            Musterland
          </p>
        </StyledContactSection>
      </main>
    </>
  );
}
const StyledWelcomeSection = styled.div`
  display: flex;
  flex-direction: column;
  height: fit-content;

  justify-content: center;
  align-items: center;
  scroll-margin-top: 100px;
  background-image: url("/images/hero-top.png");
  background-size: cover;
  background-position: center;
  background-repeat: no-repeat;
`;

const StyledWelcomeTitle = styled.h1`
  color: var(--color-secondary-1);
  padding: 2rem 2rem;
  margin: 0;
  text-align: center;
  line-height: 1.5;
  
`;
const StyledWelcomeText = styled.p`
  color: var(--color-primary-2);
  padding: 1rem 2rem;
  margin: 0;
  width: fit-content;
  text-align: center;
  font-weight: 700;
  line-height: 1.3;
  text-shadow: 1px 1px 2px rgba(235, 214, 98, 0.2);
`;

const StyledCalltoActionbutton = styled.a`
background-color: var(--color-secondary-1);
width: fit-content;
height: fit-content;
margin-top: 16px;
margin-bottom: 32px;
text-align: center;
padding: 15px 20px;
text-decoration: none;
color: var(--color-secondary-2);
border-radius: 30px;
box-shadow: 3px 3px 5px var(--color-primary-2);
font-weight: 700;
`; 

const StyledAboutUsSection = styled.div`
  display: flex;
  flex-direction: column;
  color: var(--color-secondary-2);
  background-color: var(--color-secondary-1);
  margin-top: 0;
  height: fit-content;
  justify-content: start;
  align-items: start;
  padding: 2rem;
  scroll-margin-top: 100px;
`;
const StyledTeepeeSection = styled(StyledAboutUsSection)`
  background-color: var(--color-secondary-3);
  color: var(--color-secondary-1);
  margin-top: 0;
`;
const StyledSoundJourneySection = styled(StyledAboutUsSection)`
  background-color: var(--color-secondary-2);
  color: var(--color-secondary-1);
  margin-top: 0;
`;
const StyledPriceSection = styled(StyledAboutUsSection)`
  background-color: var(--color-primary-1);
  color: var(--color-secondary-1);
  margin-top: 0;
`;
const StyledContactSection = styled(StyledAboutUsSection)`
  background-color: var(--color-secondary-1);
  margin-top: 0;
`;
