import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";

export default function Home() {
  return (
    <>
      <Head>
        <title>KlangundTipi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <StyledWelcomeSection>
          <StyledWelcomeText>
            Erlebe Sie einen Abend mit Klang und Speisen in einem traditionellen Tipi
          </StyledWelcomeText>
          <StyledWelcomeImage
            src="/images/hero-top.png"
            width={400}
            height={400}
            quality={50}
            alt="Hero Image"
            priority
          />
        </StyledWelcomeSection>
        <StyledAboutUsSection>
          <h2>über Uns</h2>
          <div>
            <p>
              Mein Name ist Christiane Wolf. Ich bin in Heidenrod - Nauroth geboren und lebe in der Wetterau in Hessen.
              Seit 20 Jahren bin ich als Ergotherapeutin tätig und weiß wie wichtig Entspannung für unsere Gesundheit
              ist. 2017 habe ich die Peter Hess- klang-Methode entdeckt und bin über die vielen Möglichkeiten der
              Klangmassagen und Klang-Fantasie-reisen fasziniert. Sie können uns helfen besser und leichter in die
              Entspannung zu kommen. Die ist auch in unseren Hirnströmen messbar.
            </p>
            <p>
              Mein Name ist Stefan Blass. Ich war über 40 Jahre selbständig in der Gastronomie tätig. Eins meiner
              Leidenschaften gehört der Kultur der Plain-Indianerstämme. Daraus erfolgte der Gedanke in einem
              Indianertipi mit interessierten Menschen gemeinsam indianische Abende zu gestalten. Da meine
              Lebensgefährtin sich seit längerem mit der Peter Hess Klangmethode auseinandersetzt kam uns der Gedanke
              die Tipiabende mit Speisen und Klangreisen zu erweitern.
            </p>
          </div>
        </StyledAboutUsSection>
        <StyledTeepeeSection>
          <h2>ein Abend im traditionellen Tipi</h2>
        </StyledTeepeeSection>
        <StyledSoundJourneySection>
          <h2>eine Reise mit Klang</h2>
        </StyledSoundJourneySection>
        <StyledPriceSection>
          <h2>unser Angebot</h2>
          <p>Genießen Sie mit Ihren Freunden/Familie einen unvergesslichen Abend am Lagerfeuer, mit Speisen und Klang in einem Tipi. Sie haben die Möglichkeit aus verschiedenen Modulen sich Ihren Abend selbst zu gestalten. 

1.  Tipianmietung ohne Service  pro Person ab zwei Personen  15 €

2. Tipiabend mit Verpflegung
    	3 Gängemenü nach Absprache und Getränke
									Preis nach Absprache

3. Tipiabend mit Klang-Fantasie-Reise (ca. 30 min.)
	Preis pro Person  für 2 Personen					  36 €
    	jede weitere Person 							   15 €

4. Tipiabend incl. Übernachtung
	(Schlafsäcke sind selbst mitzubringen) pro Person	   15 €


Feuerholz wird separat berechnet.

Anmietung für besondere Anlässe , Geburtstage, Hochzeiten Todesfälle							150€</p>
        </StyledPriceSection>
        <StyledContactSection>
          <h2>Kontakt</h2>
        </StyledContactSection>
      </main>
    </>
  );
}
const StyledWelcomeSection = styled.div`
  display: flex;
  height: 50svh;
  margin-top: 100px;
  position: relative;
  justify-content: center;
  align-items: center;
`;
const StyledWelcomeImage = styled(Image)`
  width: 100%;
  height: 50svh;
  object-fit: cover;
`;

const StyledWelcomeText = styled.h1`
  position: absolute;
  top: 5%;
  color: var(--color-secondary-1);
  padding: 2rem;
  margin: 0;
  width: fit-content;
  text-align: center;
  line-height: 1.5;
`;
const StyledAboutUsSection = styled(StyledWelcomeSection)`
  display: flex;
  flex-direction: column;
  color: var(--color-secondary-2);
  background-color: var(--color-secondary-1);
  margin-top: 0;
  height: fit-content;
  justify-content: start;
  align-items: start;
  padding: 2rem;
`;
const StyledTeepeeSection = styled(StyledAboutUsSection)`
  background-color: var(--color-secondary-3);
  color: var(--color-secondary-1);
  margin-top: 0;
`;
const StyledSoundJourneySection = styled(StyledAboutUsSection)`
  background-color: var(--color-secondary-2);
  margin-top: 0;
`;
const StyledPriceSection = styled(StyledAboutUsSection)`
  background-color: var(--color-primary-1);
  margin-top: 0;
`;
const StyledContactSection = styled(StyledAboutUsSection)`
  background-color: var(--color-primary-1);
  margin-top: 0;
`;
